apiVersion: v1
kind: ConfigMap
metadata:
  name: taskprovision-config
  namespace: taskprovision
  labels:
    app: taskprovision
    component: config
data:
  # Application settings
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"

  # AI Services
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  OLLAMA_MODEL: "qwen2.5:1.5b"

  # Database
  DATABASE_URL: "postgresql://taskprovision:password@postgres-service:5432/taskprovision"
  REDIS_URL: "redis://redis-service:6379/0"

  # Features
  QUALITY_CHECK_ENABLED: "true"
  LEAD_GENERATION_ENABLED: "true"
  PROMETHEUS_ENABLED: "true"

  # Limits
  MAX_FILE_SIZE: "10485760"  # 10MB
  RATE_LIMIT_PER_MINUTE: "60"
  MAX_CONCURRENT_TASKS: "10"

  # CORS
  CORS_ORIGINS: "http://localhost:3000,https://taskprovision.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: taskprovision-secrets
  namespace: taskprovision
  labels:
    app: taskprovision
    component: secrets
type: Opaque
stringData:
  # Security
  SECRET_KEY: "your-secret-key-change-in-production"

  # Database credentials
  POSTGRES_PASSWORD: "password"

  # External API keys (to be set during deployment)
  GITHUB_TOKEN: ""
  STRIPE_API_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  OPENAI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  SENTRY_DSN: ""

  # Email configuration
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""